name: flutter_app
description: A new Flutter project for SmartField
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

  # Firebase
  firebase_core: ^2.22.0
  # Если используешь другие пакеты Firebase, добавь их:
  # firebase_auth: ^5.1.0
  # cloud_firestore: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
